# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      build:
        steps:
        - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag containerhomepage_container-homepage $DOCKER_HUB_USER_ID/container-homepage:$CIRCLE_SHA1
            docker tag containerhomepage_container-homepage $DOCKER_HUB_USER_ID/container-homepage:latest
            docker push $DOCKER_HUB_USER_ID/container-homepage:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/container-homepage:latest 
            